#!/usr/bin/env python
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

import argparse
import sys
import htcondor

# Nagios exit status
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def main():
    args = parse_args()
    states = [STATE_OK]
    messages = []
    jobs = []

    job_attrs = [
        'JobStatus',
        'ServerTime',
        'EnteredCurrentStatus',
        'GridJobStatus',
        'GridJobId',
    ]

    try:
        coll = htcondor.Collector(args.collector)
        schedd_ad = coll.locate(htcondor.DaemonTypes.Schedd)
        schedd = htcondor.Schedd(schedd_ad)
        jobs = schedd.xquery(requirements='RoutedJob == TRUE', projection=job_attrs)
    except IOError as e:
        # Connection failed
        states.append(STATE_CRITICAL)
        messages.append(str(e))
    except Exception as e:
        # Other error
        states.append(STATE_UNKNOWN)
        messages.append(str(e))

    stats = {
        'held': 0,
        'idle': 0,
        'idle_long': 0,
        'running': 0,
    }

    # Check for held job
    for job in jobs:
        if 'JobStatus' in job:
            if job['JobStatus'] == 1:
                stats['idle'] += 1
                continue
            if job['JobStatus'] == 2:
                stats['running'] += 1
                continue
            if job['JobStatus'] == 5 and job['HoldReasonCode'] != 16:
                stats['held'] += 1
                continue

        # Has the routed job been idle for longer than 10 minutes, ie not submitted
        if job['JobStatus'] == 1 and (job['ServerTime'] - job['EnteredCurrentStatus']) > 60*10 and 'GridJobStatus' not in job:
            stats['idle_long'] += 1
            continue

        # Check for grid job id
        if 'GridJobId' in job:
            # Check for remote
            gridJobId = job['GridJobId']
            try:
                remote_id = gridJobId.split(" ")[-1:]
            except:
                pass

    if jobs:
        messages.append("{} running, {} idle, {} held jobs".format(stats['running'], stats['idle'], stats['held']))

    if stats['held'] > 0:
        states.append(STATE_CRITICAL)
    if stats['idle_long'] > 0:
        messages.append("{} Long idle Job".format(stats['idle_long']))
        states.append(STATE_CRITICAL)

    state = max(states)
    message = ', '.join(messages)

    perf_data = ' |running=%(running)d idle=%(idle)d held=%(held)d' % stats

    if not message:
        message = 'OK'

    print(message + perf_data)
    sys.exit(state)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('collector')
    return parser.parse_args()

if __name__ == "__main__":
    # Run script as main
    main()
